version: '3.4'

services:
  ecsfront:
    image: ecsfront
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bundle exec rails s -p 4000 -b '0.0.0.0'
    ports:
      - 4000:4000
    # network_mode: host
    extra_hosts:
      - "host.docker.internal:host-gateway"